default: &default
  adapter: libsql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    path: storage/development.sqlite3
  fosm:
    <<: *default
    path: storage/fosm_development.sqlite3
    migrations_paths: db/fosm_migrate
  cache:
    <<: *default
    path: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    path: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    path: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    path: storage/test.sqlite3
  fosm:
    <<: *default
    path: storage/fosm_test.sqlite3
    migrations_paths: db/fosm_migrate
  cache:
    <<: *default
    path: storage/test_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    path: storage/test_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    path: storage/test_cable.sqlite3
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>
  fosm:
    adapter: libsql
    url: <%= ENV['TURSO_DATABASE_URL'] %>
    auth_token: <%= ENV['TURSO_AUTH_TOKEN'] %>
    path: storage/fosm_production.sqlite3
    migrations_paths: db/fosm_migrate
  cache:
    <<: *primary_production
    url: <%= URI.parse(ENV['DATABASE_URL']).tap { |u| u.path += '_cache' } if ENV['DATABASE_URL'] && Rails.env.production? %>
    database_tasks: true
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    url: <%= URI.parse(ENV['DATABASE_URL']).tap { |u| u.path += '_queue' } if ENV['DATABASE_URL'] && Rails.env.production? %>
    database_tasks: true
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= URI.parse(ENV['DATABASE_URL']).tap { |u| u.path += '_cable' } if ENV['DATABASE_URL'] && Rails.env.production? %>
    database_tasks: true
    migrations_paths: db/cable_migrate
